server.port=8888

#spring.profiles.active=native

spring.cloud.config.server.git.uri=D:\\Localrepo
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.instance.hostname= localhost
